### PR TITLE
Add Typings

### PR DESCRIPTION
**Pull request by SteveALee**
This is incomplete but enough for me to use in my project without use of `any` or other hacks.

### CODE REVIEW

**Comment by atomrc** [comment]
Nice ... Types!!! :)

Could you try to understand why the `npm install` won't work on CI? Seems to be a problem with the version of xstream.

**Comment by SteveALee** [comment]
I can't view the details - server not found :(

**Comment by SteveALee** [comment]
But the reason appears to be version was specified as >1.2.3 where 1.2.3 was latest except for a rc version. thus the value specified in package.json should probably be >=1.2.3 if that is possible.

It works fine for me but I'm on npm 5.x where as travis env was 3.x

**Comment by SteveALee** [comment]
I updated my branch but the CI doesn't seem to have re - run

**Comment by SteveALee** [comment]
Aha!

**Comment by atomrc** [comment]
Awesome, let's merge!! Thanks Steve : )

**Pull request merged**
